In [1]:
import numpy as np

In [2]:
def Trapezoidal(f, a, b):
    answ = []
    h_arr = []
    for k in range(1,5):
        n = 2**k + 1
        h = (b-a)/float(n)
        s = 0.5*(f(a) + f(b))
        for i in range(1,n,1):
            s = s + f(a + i*h)
        answ.append(h*s)
        h_arr.append(h)
        
    return answ, h_arr

def f(x):
    return x**(3/5)

a = 0
b = 1

result, h_arr = Trapezoidal(f, a, b)
exact1 = 0.625
err1 = abs(exact1-np.asarray(result))


In [3]:
def f2(x):
    return x**(8/5)
result2, h_arr2 = Trapezoidal(f2, a, b)
exact2 = 0.3846153846153846
err2 = abs(exact2-np.asarray(result2))

def f3(x):
    return x**(13/5)
result3, h_arr3 = Trapezoidal(f3, a, b)

exact3 = 0.2777777777777778
err3 = abs(exact3-np.asarray(result3))


In [4]:
import pandas as pd
df_trapez = pd.DataFrame({'Values': result,'Error': err1})
df_trapez2 = pd.DataFrame({'Values': result2,'Error': err2})
df_trapez3 = pd.DataFrame({'Values': result3,'Error': err3})

In [5]:
df_trapez

Values     Error
0  0.600445  0.024555
1  0.613704  0.011296
2  0.620426  0.004574
3  0.623297  0.001703

In [6]:
df_trapez2

Values     Error
0  0.398376  0.013761
1  0.389669  0.005053
2  0.386201  0.001585
3  0.385065  0.000450

In [7]:
df_trapez3

Values     Error
0  0.301981  0.024203
1  0.286466  0.008688
2  0.280455  0.002678
3  0.278528  0.000750

In [8]:
def simpson(a, b, f):
    sum = 0
    ans = []
    for m in range(1,5):
        sum = 0
        n = 2**m 
        inc = (b - a) / n
        for k in range(n+1):
            x = a + (k * inc)
            summand = f(x)
            if (k != 0) and (k != n):
                summand *= (2 + (2 * (k % 2)))
            sum += summand
        ans.append(((b - a) / (3 * n)) * sum)
    return ans

In [9]:
a = 0
b=  1
result_simp = simpson(a,b,f)
result_simp2 = simpson(a,b,f2)
result_simp3 = simpson(a,b,f3)

In [10]:
err_simp = abs(exact1-np.asarray(result_simp))
err2_simp = abs(exact2-np.asarray(result_simp2))
err3_simp = abs(exact3-np.asarray(result_simp3))

In [16]:
print(err3_simp/(np.asarray(h_arr))**4)
print(err2_simp/(np.asarray(h_arr))**4)
print(err_simp/(np.asarray(h_arr))**4)

[0.0933216  0.06969934 0.06734404 0.07632656]
[0.15951064 0.21060932 0.37007598 0.78144794]
[ 1.49828641  3.82945449 13.27307637 55.74772867]


In [17]:
df_simp = pd.DataFrame({'Values': result_simp,'Error': err_simp})
df_simp2 = pd.DataFrame({'Values': result_simp2,'Error': err2_simp})
df_simp3 = pd.DataFrame({'Values': result_simp3,'Error': err3_simp})

In [18]:
df_simp

Values     Error
0  0.606503  0.018497
1  0.618873  0.006127
2  0.622977  0.002023
3  0.624333  0.000667

In [19]:
df_simp2

Values     Error
0  0.386585  0.001969
1  0.384952  0.000337
2  0.384672  0.000056
3  0.384625  0.000009

In [20]:
df_simp3

Values         Error
0  0.276626  1.152119e-03
1  0.277666  1.115189e-04
2  0.277768  1.026430e-05
3  0.277777  9.138607e-07